name: BukkitPlugin
version: '${project.version}'
main: nl.arnoutpullen.bukkitplugin.BukkitPlugin
api-version: 1.15
authors: [ ArnoutPullen ]
website: https://arnoutpullen.nl
commands:
  msg:
    description: Send message to player
    usage: /msg [player] [message]
  ping:
    description: Ping
    usage: /ping