name: BukkitPlugin
version: '${project.version}'
main: nl.arnoutpullen.bukkitplugin.BukkitPlugin
api-version: 1.15
authors: [ ArnoutPullen ]
website: https://arnoutpullen.nl
commands:
  enderchest:
    description: Open EnderChest
    usage: /enderchest [player]
  heal:
    description: Heal player
    usage: /heal [player]
  msg:
    description: Send message to player
    usage: /msg [player] [message]
  ping:
    description: Ping
    usage: /ping